using System;
namespace HutongGames.PlayMakerEditor
{
	public enum WikiPages
	{
		Home = 1,
		ReleaseNotes = 311,
		MainEditorWindow = 129,
		DebuggingToolbar = 139,
		StateInspector = 151,
		Preferences = 117,
		EventManager = 148,
		EventBrowser = 642,
		VariableManager = 50,
		ActivateGameObject = 52,
		AddAnimationClip = 443,
		AddComponent = 585,
		AddExplosionForce = 315,
		AddForce,
		AddMixingTransform = 807,
		AddScript = 53,
		AddTorque = 317,
		AnimateFloat = 4,
		AnimateColor = 559,
		AnimateFloatV2 = 674,
		AnimateRect,
		AnimateVector3 = 562,
		CurveColor,
		CurveFloat,
		CurveRect = 676,
		CurveVector3 = 565,
		EaseColor,
		EaseFloat,
		EaseRect = 677,
		EaseVector3 = 568,
		AnimationSettings = 5,
		AnyKey = 29,
		ApplicationQuit = 672,
		ApplicationRunInBackground = 808,
		ArrayAdd = 1198,
		ArrayAddRange,
		ArrayClear,
		ArrayContains,
		ArrayDeleteAt,
		ArrayForEach,
		ArrayGet,
		ArrayGetNext,
		ArrayGetRandom,
		ArrayLength,
		ArrayResize,
		ArrayReverse,
		ArraySet,
		ArrayShuffle,
		ArraySort,
		ArrayTransferValue,
		FsmArraySet,
		AudioMute = 461,
		AudioPause,
		AudioPlay,
		AudioStop,
		AxisEvent = 681,
		BlendAnimation = 18,
		Blink = 202,
		BoolAllTrue = 469,
		BoolAnyTrue,
		BoolChanged = 517,
		BoolFlip = 237,
		BoolNoneTrue = 471,
		BoolOperator = 524,
		BoolTest = 76,
		BroadcastEvent = 493,
		BuildString = 372,
		CallMethod = 1139,
		CallStaticMethod = 1219,
		CameraFadeIn = 185,
		CameraFadeOut,
		CapturePoseAsAnimationClip = 809,
		CollisionEvent = 30,
		ColorInterpolate = 418,
		ColorRamp = 363,
		Comment = 213,
		ControllerIsGrounded = 536,
		ControllerMove = 521,
		ControllerSettings = 810,
		ControllerSimpleMove = 522,
		ConvertBoolToColor = 499,
		ConvertBoolToFloat = 501,
		ConvertBoolToInt = 500,
		ConvertBoolToString = 356,
		ConvertEnumToString = 1259,
		ConvertFloatToInt = 359,
		ConvertFloatToString,
		ConvertIntToFloat = 357,
		ConvertIntToString,
		ConvertMaterialToObject = 1184,
		ConvertSecondsToString = 1231,
		ConvertStringToInt = 811,
		CreateEmptyObject = 1260,
		CreateObject = 61,
		CutToCamera = 103,
		DebugBool = 22,
		DebugDrawShape = 1185,
		DebugEnum = 1215,
		DebugFloat = 23,
		DebugFsmVariable = 1186,
		DebugGameObject = 24,
		DebugInt,
		DebugLog,
		DebugObject = 1187,
		DebugVector3 = 502,
		DestroyComponent = 586,
		DestroyObject = 62,
		DestroyObjects = 1232,
		DestroySelf = 214,
		DetachChildren = 63,
		DeviceOrientationEvent = 573,
		DevicePlayFullScreenMovie = 1120,
		DeviceShakeEvent = 678,
		DeviceVibrate = 812,
		DontDestroyOnLoad = 314,
		DrawDebugLine = 503,
		DrawDebugRay,
		DrawFullscreenColor = 419,
		DrawStateLabel = 224,
		DrawTexture = 331,
		EnableAnimation = 94,
		EnableBehaviour = 54,
		EnableFSM,
		EnableFog = 395,
		EnableGUI = 590,
		EnumCompare = 1217,
		EnumSwitch,
		Explosion = 318,
		FindChild = 64,
		FindClosest,
		FindGameObject = 51,
		FinishFSM = 1140,
		Flicker = 203,
		FloatAbs = 238,
		FloatAdd = 79,
		FloatAddMultiple = 1261,
		FloatChanged = 518,
		FloatClamp = 77,
		FloatCompare = 80,
		FloatDivide = 227,
		FloatInterpolate = 239,
		FloatMultiply = 228,
		FloatOperator = 81,
		FloatSignTest = 240,
		FloatSubtract = 687,
		FloatSwitch = 515,
		FormatString = 1121,
		ForwardAllEvents = 1262,
		ForwardEvent,
		FsmStateSwitch = 487,
		FsmStateTest = 106,
		GUIBox = 509,
		GUIButton = 508,
		GUIElementHitTest = 814,
		GUIHorizontalSlider = 506,
		GUILabel,
		GUILayoutBeginArea = 423,
		GUILayoutBeginAreaFollowObject = 422,
		GUILayoutBeginCentered = 510,
		GUILayoutBeginHorizontal = 424,
		GUILayoutBeginScrollView = 1248,
		GUILayoutBeginVertical = 425,
		GUILayoutBox,
		GUILayoutButton,
		GUILayoutEndArea,
		GUILayoutEndCentered = 511,
		GUILayoutEndHorizontal = 429,
		GUILayoutEndScrollView = 1249,
		GUILayoutEndVertical = 430,
		GUILayoutFlexibleSpace,
		GUILayoutFloatField = 815,
		GUILayoutFloatLabel,
		GUILayoutHorizontalSlider = 432,
		GUILayoutIntField = 817,
		GUILayoutIntLabel,
		GUILayoutLabel = 433,
		GUILayoutPasswordField = 1308,
		GUILayoutRepeatButton = 434,
		GUILayoutSpace,
		GUILayoutTextField,
		GUILayoutTextLabel = 819,
		GUILayoutToggle = 437,
		GUILayoutToolbar,
		GUILayoutVerticalSlider,
		GUITooltip = 420,
		GUIVerticalSlider = 505,
		GameObjectChanged = 516,
		GameObjectCompare = 488,
		GameObjectCompareTag = 218,
		GameObjectHasChildren = 217,
		GameObjectIsChildOf = 69,
		GameObjectIsNull,
		GameObjectIsVisible = 233,
		GameObjectTagSwitch = 489,
		GetAngleToTarget = 494,
		GetAxis = 192,
		GetAxisVector = 453,
		GetButton = 193,
		GetButtonDown = 190,
		GetButtonUp,
		GetChild = 66,
		GetChildCount = 215,
		GetChildNum = 67,
		GetCollisionInfo = 369,
		GetColorRGBA = 364,
		GetComponent = 820,
		GetControllerCollisionFlags = 520,
		GetControllerHitInfo = 370,
		GetDeviceAcceleration = 574,
		GetDeviceRoll,
		GetDistance = 187,
		GetEventInfo = 530,
		GetFsmBool = 107,
		GetFsmColor = 532,
		GetFsmEnum = 1253,
		GetFsmFloat = 109,
		GetFsmGameObject,
		GetFsmInt = 108,
		GetFsmMaterial = 699,
		GetFsmObject,
		GetFsmQuaternion,
		GetFsmRect,
		GetFsmState = 480,
		GetFsmString = 346,
		GetFsmTexture = 703,
		GetFsmVariable = 1265,
		GetFsmVariables,
		GetFsmVector2 = 1123,
		GetFsmVector3 = 533,
		GetIPhoneSettings = 576,
		GetKey = 348,
		GetKeyDown = 98,
		GetKeyUp,
		GetLastEvent = 821,
		GetLayer = 587,
		GetLocationInfo = 577,
		GetMainCamera = 569,
		GetMass = 319,
		GetMaterial = 684,
		GetMaterialTexture,
		GetMouseButton = 194,
		GetMouseButtonDown,
		GetMouseButtonUp,
		GetMouseX = 225,
		GetMouseY,
		GetName = 444,
		GetNextChild = 822,
		GetOwner = 588,
		GetParent = 68,
		GetPosition = 235,
		GetPreviousStateName = 704,
		GetProperty = 695,
		GetRandomChild = 313,
		GetRandomObject = 312,
		GetRaycastHitInfo = 491,
		GetRectFields = 691,
		GetRoot = 485,
		GetRotation = 236,
		GetScale = 711,
		GetScreenHeight = 447,
		GetScreenWidth = 446,
		GetSpeed = 328,
		GetStringLeft = 341,
		GetStringLength = 340,
		GetStringRight = 342,
		GetSubstring,
		GetSystemDateTime = 823,
		GetTag = 525,
		GetTagCount = 216,
		GetTimeInfo = 496,
		GetTouchCount = 578,
		GetTouchInfo,
		GetTransform = 1127,
		GetTriggerInfo = 371,
		GetVector3XYZ = 376,
		GetVectorLength = 1126,
		GetVelocity = 320,
		GetVertexCount = 825,
		GetVertexPosition,
		GotoPreviousState = 705,
		HasComponent = 589,
		IntAdd = 82,
		IntChanged = 514,
		IntClamp = 78,
		IntCompare = 83,
		IntOperator,
		IntSwitch = 454,
		InverseTransformDirection = 479,
		InverseTransformPoint = 478,
		InvokeMethod = 56,
		IsKinematic = 321,
		IsSleeping,
		KillDelayedEvents = 1125,
		LoadLevel = 71,
		LoadLevelNum,
		LookAt = 100,
		MouseLook = 682,
		MousePick = 415,
		MousePickEvent = 32,
		MoveObject = 1228,
		MoveTowards = 101,
		MovieTextureAudioSettings = 472,
		MasterServerClearHostList = 765,
		MasterServerGetHostCount,
		MasterServerGetHostData,
		MasterServerGetNextHostData,
		MasterServerGetProperties,
		MasterServerRegisterHost,
		MasterServerRequestHostList,
		MasterServerSetProperties,
		MasterServerUnregisterHost,
		NetworkCloseConnection,
		NetworkConnect,
		NetworkDestroy,
		NetworkDisconnect,
		NetworkGetPlayerPing,
		NetworkGetConnectedPlayerProperties,
		NetworkGetConnectionsCount,
		NetworkGetIsMessageQueueRunning,
		NetworkGetLastPing,
		NetworkGetLocalPlayerProperties,
		NetworkGetMaximumConnections,
		NetworkGetMessagePlayerProperties,
		NetworkGetMinimumAllocatableViewIDs,
		NetworkGetOnFailedToConnectProperties,
		NetworkGetNextConnectedPlayerProperties,
		NetworkGetSendRate,
		NetworkGetTime,
		NetworkHavePublicIpAddress,
		NetworkInitializeServer,
		NetworkInstantiate,
		NetworkIsClient,
		NetworkIsServer,
		NetworkPeerTypeSwitch,
		NetworkSetIsMessageQueueRunning,
		NetworkSetLevelPrefix,
		NetworkSetLogLevel,
		NetworkSetMaximumConnections,
		NetworkSetMinimumAllocatableViewIDs,
		NetworkSetSendRate,
		NetworkViewIsMine,
		NetworkViewRemoveRPCs,
		SendRemoteEvent,
		StartServer,
		NextFrameEvent = 349,
		ObjectCompare = 683,
		PauseMovieTexture = 451,
		PerSecond = 207,
		AddForce2d = 1268,
		AddTorque2d,
		Collision2dEvent,
		GetCollision2dInfo,
		GetMass2d,
		GetNextLineCast2d,
		GetNextOverlapArea2d,
		GetNextOverlapCircle2d,
		GetNextOverlapPoint2d,
		GetNextRayCast2d,
		GetRayCastHit2dInfo,
		GetSpeed2d,
		GetTrigger2dInfo,
		GetVelocity2d,
		IsFixedAngle2d,
		IsKinematic2d,
		IsSleeping2d,
		LineCast2d,
		LookAt2d = 1299,
		LookAt2dGameObject,
		MousePick2d,
		MousePick2dEvent,
		RayCast2d = 1286,
		ScreenPick2d = 1303,
		SetGravity2d = 1287,
		SetGravity2dScale,
		SetHingeJoint2dProperties,
		SetIsFixedAngle2d,
		SetIsKinematic2d,
		SetMass2d,
		SetVelocity2d,
		SetWheelJoint2dProperties,
		Sleep2d,
		SmoothLookAt2d = 1305,
		TouchObject2dEvent = 1304,
		Trigger2dEvent = 1296,
		WakeAllRigidBodies2d,
		WakeUp2d,
		PlayAnimation = 19,
		PlayRandomAnimation = 1124,
		PlayMovieTexture = 450,
		PlayRandomSound = 212,
		PlaySound = 21,
		PlayerPrefsDeleteAll = 549,
		PlayerPrefsDeleteKey = 551,
		PlayerPrefsGetFloat = 557,
		PlayerPrefsGetInt = 552,
		PlayerPrefsGetString = 555,
		PlayerPrefsHasKey,
		PlayerPrefsSetFloat = 550,
		PlayerPrefsSetInt = 553,
		PlayerPrefsSetString,
		RebuildTextures = 828,
		SetProceduralBoolean,
		SetProceduralColor,
		SetProceduralFloat,
		ProjectLocationToMap = 580,
		GetQuaternionEulerAngles = 1329,
		GetQuaternionFromRotation,
		GetQuaternionMultipliedByQuaternion,
		GetQuaternionMultipliedByVector,
		QuaternionAngleAxis,
		QuaternionEuler,
		QuaternionInverse,
		QuaternionLerp,
		QuaternionLookRotation,
		QuaternionLowPassFilter,
		QuaternionRotateTowards,
		QuaternionSlerp,
		RandomBool = 85,
		RandomEvent = 33,
		RandomFloat = 86,
		RandomInt,
		RandomWait = 1227,
		Raycast = 492,
		RaycastAll = 1233,
		RectContains = 692,
		RectOverlaps = 1246,
		RemoveMixingTransform = 832,
		ResetGUIMatrix = 1250,
		ResetInputAxes = 486,
		RestartLevel = 1341,
		RewindAnimation = 833,
		Rotate = 197,
		RotateGUI = 334,
		RunFSM = 1138,
		SampleCurve = 241,
		ScaleGUI = 335,
		ScaleTime = 95,
		ScreenPick = 591,
		ScreenToWorldPoint = 570,
		SelectRandomColor = 365,
		SelectRandomGameObject = 442,
		SelectRandomString = 373,
		SelectRandomVector3 = 377,
		SendEvent = 34,
		SendEventByName = 834,
		SendEventToFsm = 35,
		SendMessage = 57,
		SendRandomEvent = 481,
		SequenceEvent = 36,
		SetAmbientLight = 396,
		SetAnimationSpeed = 16,
		SetAnimationTime,
		SetAnimationWeight = 91,
		SetAudioClip = 465,
		SetAudioLoop,
		SetAudioPitch,
		SetAudioVolume,
		SetBackgroundColor = 473,
		SetBoolValue = 88,
		SetCameraCullingMask = 835,
		SetCameraFOV = 474,
		SetColorRGBA = 366,
		SetColorValue,
		SetDrag = 1230,
		SetEnumValue = 1216,
		SetEventData = 531,
		SetEventTarget = 713,
		SetFlareStrength = 397,
		SetFloatValue = 89,
		SetFogColor = 398,
		SetFogDensity,
		SetFsmBool = 111,
		SetFsmColor = 534,
		SetFsmEnum = 1247,
		SetFsmFloat = 113,
		SetFsmGameObject,
		SetFsmInt = 112,
		SetFsmMaterial = 706,
		SetFsmObject,
		SetFsmQuaternion,
		SetFsmRect,
		SetFsmString = 347,
		SetFsmTexture = 710,
		SetFsmVariable = 1251,
		SetFsmVector2 = 1122,
		SetFsmVector3 = 535,
		SetGUIAlpha = 402,
		SetGUIBackgroundColor,
		SetGUIColor,
		SetGUIContentColor,
		SetGUIDepth = 336,
		SetGUISkin,
		SetGUIText = 220,
		SetGUITexture,
		SetGUITextureAlpha,
		SetGUITextureColor,
		SetGameObject = 97,
		SetGameVolume = 96,
		SetGravity = 230,
		SetHaloStrength = 400,
		SetIntFromFloat = 229,
		SetIntValue = 90,
		SetIsKinematic = 323,
		SetJointConnectedBody = 1188,
		SetLayer = 632,
		SetLightColor = 385,
		SetLightCookie,
		SetLightFlare,
		SetLightIntensity,
		SetLightRange,
		SetLightSpotAngle,
		SetLightType,
		SetMainCamera = 1189,
		SetMass = 324,
		SetMaterial = 104,
		SetMaterialColor = 380,
		SetMaterialFloat = 406,
		SetMaterialMovieTexture = 836,
		SetMaterialTexture = 407,
		SetMouseCursor = 219,
		SetName = 633,
		SetObjectValue = 697,
		SetParent = 73,
		SetPosition = 102,
		SetProperty = 696,
		SetRandomMaterial = 368,
		SetRandomRotation = 242,
		SetRectFields = 693,
		SetRectValue,
		SetRotation = 199,
		SetScale,
		SetShadowStrength = 392,
		SetSkybox = 401,
		SetStringValue = 344,
		SetTag = 74,
		SetTagsOnChildren = 1252,
		SetTextureOffset = 381,
		SetTextureScale,
		SetVector3Value = 378,
		SetVector3XYZ,
		SetVelocity = 325,
		SetVisibility = 686,
		Sleep = 326,
		SmoothFollowAction = 1190,
		SmoothLookAt = 458,
		SmoothLookAtDirection = 457,
		StartCoroutine = 58,
		StartLocationServiceUpdates = 581,
		StopAnimation = 20,
		StopLocationServiceUpdates = 582,
		StopMovieTexture = 452,
		StringJoin = 1306,
		StringSplit,
		StringChanged = 526,
		StringCompare = 408,
		StringContains = 513,
		StringReplace = 345,
		StringSwitch = 455,
		SwipeGestureEvent = 583,
		TakeScreenshot = 105,
		TouchEvent = 584,
		TouchGUIEvent = 679,
		TouchObjectEvent,
		TransformDirection = 477,
		TransformInputToWorldSpace = 1191,
		TransformPoint = 476,
		Translate = 201,
		TriggerEvent = 37,
		UseGUILayout = 512,
		UseGravity = 231,
		DebugVector2 = 1256,
		GetVector2Length = 1309,
		GetVector2XY,
		SelectRandomVector2,
		SetVector2Value,
		SetVector2XY,
		Vector2Add,
		Vector2AddXY,
		Vector2ClampMagnitude,
		Vector2HighPassFilter,
		Vector2Interpolate,
		Vector2Invert,
		Vector2Lerp,
		Vector2LowPassFilter,
		Vector2MoveTowards,
		Vector2Multiply,
		Vector2Normalize,
		Vector2Operator,
		Vector2PerSecond,
		Vector2RotateTowards,
		Vector2Subtract,
		Vector3Add = 459,
		Vector3AddXYZ = 631,
		Vector3ClampMagnitude = 484,
		Vector3HighPassFilter = 592,
		Vector3Interpolate = 482,
		Vector3Invert,
		Vector3Lerp = 837,
		Vector3LowPassFilter = 593,
		Vector3Multiply = 416,
		Vector3Normalize = 594,
		Vector3Operator = 690,
		Vector3PerSecond = 527,
		Vector3RotateTowards,
		Vector3Subtract = 460,
		WWWObject = 698,
		Wait = 234,
		WakeAllRigidBodies = 232,
		WakeUp = 327,
		WorldToScreenPoint = 571,
		iTweenLookFrom = 595,
		iTweenLookTo,
		iTweenLookUpdate,
		iTweenMoveAdd,
		iTweenMoveBy,
		iTweenMoveFrom,
		iTweenMoveTo,
		iTweenMoveUpdate,
		iTweenPause,
		iTweenPunchPosition,
		iTweenPunchRotation,
		iTweenPunchScale,
		iTweenResume,
		iTweenRotateAdd,
		iTweenRotateBy,
		iTweenRotateFrom,
		iTweenRotateTo,
		iTweenRotateUpdate,
		iTweenScaleAdd,
		iTweenScaleBy,
		iTweenScaleFrom,
		iTweenScaleTo,
		iTweenScaleUpdate,
		iTweenShakePosition,
		iTweenShakeRotation,
		iTweenShakeScale,
		iTweenStop,
		MissingAction = 838,
		ConditionalExpression = 1226,
		AnimatorCrossFade = 1457,
		AnimatorInterruptMatchTarget = 1358,
		AnimatorMatchTarget,
		AnimatorPlay,
		AnimatorStartPlayback,
		AnimatorStartRecording,
		AnimatorStopPlayback,
		AnimatorStopRecording,
		GetAnimatorApplyRootMotion,
		GetAnimatorBody,
		GetAnimatorBoneGameObject,
		GetAnimatorBool,
		GetAnimatorCullingMode,
		GetAnimatorCurrentStateInfo,
		GetAnimatorCurrentStateInfoIsName,
		GetAnimatorCurrentStateInfoIsTag,
		GetAnimatorCurrentTransitionInfo,
		GetAnimatorCurrentTransitionInfoIsName,
		GetAnimatorCurrentTransitionInfoIsUserName,
		GetAnimatorDelta,
		GetAnimatorFeetPivotActive,
		GetAnimatorFloat,
		GetAnimatorGravityWeight,
		GetAnimatorHumanScale,
		GetAnimatorIKGoal,
		GetAnimatorInt,
		GetAnimatorIsHuman,
		GetAnimatorIsLayerInTransition,
		GetAnimatorIsMatchingTarget,
		GetAnimatorIsParameterControlledByCurve,
		GetAnimatorLayerCount,
		GetAnimatorLayerName,
		GetAnimatorLayerWeight,
		GetAnimatorLayersAffectMassCenter,
		GetAnimatorLeftFootBottomHeight,
		GetAnimatorNextStateInfo,
		GetAnimatorPivot,
		GetAnimatorPlayBackSpeed,
		GetAnimatorPlayBackTime,
		GetAnimatorRightFootBottomHeight,
		GetAnimatorRoot,
		GetAnimatorSpeed,
		GetAnimatorTarget,
		NavMeshAgentAnimatorSynchronizer,
		SetAnimatorApplyRootMotion,
		SetAnimatorBody,
		SetAnimatorBool,
		SetAnimatorCullingMode,
		SetAnimatorFeetPivotActive,
		SetAnimatorFloat,
		SetAnimatorIKGoal,
		SetAnimatorInt,
		SetAnimatorLayerWeight,
		SetAnimatorLayersAffectMassCenter,
		SetAnimatorLookAt,
		SetAnimatorPlayBackSpeed,
		SetAnimatorPlayBackTime,
		SetAnimatorSpeed,
		SetAnimatorStabilizeFeet,
		SetAnimatorTarget,
		SetAnimatorTrigger,
		GUILayoutConfirmPasswordField = 1352,
		GUILayoutEmailField,
		GetACosine = 1343,
		GetASine,
		GetAtan = 145,
		GetAtan2 = 1346,
		GetAtan2FromVector2,
		GetAtan2FromVector3,
		GetCosine,
		GetSine,
		GetTan,
		SetCollider2dIsTrigger = 1419,
		QuaternionCompare = 1424
	}
}
